name: Test and publish

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_nginx_config:
    name: Test nginx config
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: nginx:1.31.0-alpine@sha256:c22e76a97fe5bacad9d58bad0a96e903480c05f8dee30884b14550530ddd25a9
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Generate and validate nginx config
        run: |
          cp nginx.conf.template /etc/nginx/nginx.conf.template
          cp entrypoint.sh /entrypoint.sh
          chmod +x /entrypoint.sh
          REDIRECT_URL=https://example.com /entrypoint.sh nginx -t

  lint_dockerfile:
    name: Lint Dockerfile
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5

  publish:
    name: Publish Release and Docker image
    needs:
      - test_nginx_config
      - lint_dockerfile
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Publish Docker image
        uses: ffflorian/actions/docker-image-release@afaeca25b74a95b591bf5a168e042e20ebebcfbf
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_author: "ffflorian"
          git_email: "git@ffflorian.de"
