name: Main

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_nginx_config:
    name: Test nginx config
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: nginx:1.31.0-alpine@sha256:c22e76a97fe5bacad9d58bad0a96e903480c05f8dee30884b14550530ddd25a9
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Generate and validate nginx config
        run: |
          cp nginx.conf.template /tmp/nginx.conf.template
          cp entrypoint.sh /entrypoint.sh
          chmod +x /entrypoint.sh
          REDIRECT_URL=https://example.com /entrypoint.sh nginx -t

  lint_dockerfile:
    name: Lint Dockerfile
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5

  build_dockerfile:
    name: Build Docker image
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5

      - name: Build Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          push: false

  publish:
    name: Publish Release and Docker image
    needs:
      - test_nginx_config
      - lint_dockerfile
      - build_dockerfile
    permissions:
      contents: write
      packages: write
      issues: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Publish Release and Docker image
        uses: ffflorian/actions/docker-image-release@c9a3071b2d17985d88f3bbaeab838871d9b61bdd
        with:
          DOCKER_TOKEN: ${{ secrets.DOCKER_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_author: 'ffflorian'
          git_email: 'git@ffflorian.de'
